import numpy as np
import matplotlib.pyplot as plt 
import os
import sys

def Plot_Varying_level_comp(txtdir, k):

	TC_R_imp_avg       = np.loadtxt(txtdir + "/TC_R_imp_avg" + str(k) + ".txt")
	TC_R_unalt_avg     = np.loadtxt(txtdir + "/TC_R_unalt_avg" + str(k) + ".txt")
	TC_R_imp_rms       = np.loadtxt(txtdir + "/TC_R_imp_rms" + str(k) + ".txt")
	TC_R_unalt_rms     = np.loadtxt(txtdir + "/TC_R_unalt_rms" + str(k) + ".txt")

	TC_Phi_1_imp_avg   = np.loadtxt(txtdir + "/TC_Phi_1_imp_avg" + str(k) + ".txt")
	TC_Phi_1_unalt_avg = np.loadtxt(txtdir + "/TC_Phi_1_unalt_avg" + str(k) + ".txt")
	TC_Phi_1_imp_rms   = np.loadtxt(txtdir + "/TC_Phi_1_imp_rms" + str(k) + ".txt")
	TC_Phi_1_unalt_rms = np.loadtxt(txtdir + "/TC_Phi_1_unalt_rms" + str(k) + ".txt")

	TC_Phi_5_imp_avg   = np.loadtxt(txtdir + "/TC_Phi_5_imp_avg" + str(k) + ".txt")
	TC_Phi_5_unalt_avg = np.loadtxt(txtdir + "/TC_Phi_5_unalt_avg" + str(k) + ".txt")        
	TC_Phi_5_imp_rms   = np.loadtxt(txtdir + "/TC_Phi_5_imp_rms" + str(k) + ".txt")
	TC_Phi_5_unalt_rms = np.loadtxt(txtdir + "/TC_Phi_5_unalt_rms" + str(k) + ".txt")

	TC_A_imp_avg       = np.loadtxt(txtdir + "/TC_A_imp_avg" + str(k) + ".txt")
	TC_A_unalt_avg     = np.loadtxt(txtdir + "/TC_A_unalt_avg" + str(k) + ".txt")
	TC_A_imp_rms       = np.loadtxt(txtdir + "/TC_A_imp_rms" + str(k) + ".txt")
	TC_A_unalt_rms     = np.loadtxt(txtdir + "/TC_A_unalt_rms" + str(k) + ".txt")

	l_frac_0_arr       = np.loadtxt(txtdir + "/l_frac_0_arr" + str(k) + ".txt")
	l_frac_1_arr       = np.loadtxt(txtdir + "/l_frac_1_arr" + str(k) + ".txt")

	cont_levs          = 100

	# ----------------- Plot R
	fig_R    	       = plt.figure()
	TC_R_Norm          = np.divide(TC_R_imp_avg, TC_R_unalt_avg)
	plt.contourf(l_frac_0_arr, l_frac_1_arr, TC_R_Norm, cont_levs)
	cbar 			   = plt.colorbar()
	cbar.set_label('${T_{imp}}/{T_{unalt}}$')
	plt.xticks(l_frac_0_arr)
	plt.yticks(l_frac_1_arr)
	plt.xlabel('$l_{0}$')
	plt.ylabel('$l_{1}$')
	plt.title('R Efficiency')
	plt.set_cmap('bwr')

	fig_R_imp_rms      = plt.figure()
	plt.contourf(l_frac_0_arr, l_frac_1_arr, TC_R_imp_rms, cont_levs)
	plt.colorbar()
	plt.xticks(l_frac_0_arr)
	plt.yticks(l_frac_1_arr)
	plt.xlabel('$l_{0}$')
	plt.ylabel('$l_{1}$')
	plt.title('R Implemented RMS')
	plt.set_cmap('bwr')

	fig_R_unalt_rms     = plt.figure()
	plt.contourf(l_frac_0_arr, l_frac_1_arr, TC_R_unalt_rms, cont_levs)
	plt.colorbar()
	plt.xticks(l_frac_0_arr)
	plt.yticks(l_frac_1_arr)
	plt.xlabel('$l_{0}$')
	plt.ylabel('$l_{1}$')
	plt.title('R Unaltered RMS')
	plt.set_cmap('bwr')

	# ----------------- Plot Phi 1
	fig_Phi_1	           = plt.figure()
	TC_Phi_1_Norm          = np.divide(TC_Phi_1_imp_avg, TC_Phi_1_unalt_avg)
	plt.contourf(l_frac_0_arr, l_frac_1_arr, TC_Phi_1_Norm, cont_levs)
	cbar 			       = plt.colorbar()
	cbar.set_label('${T_{imp}}/{T_{unalt}}$')
	plt.xticks(l_frac_0_arr)
	plt.yticks(l_frac_1_arr)
	plt.xlabel('$l_{0}$')
	plt.ylabel('$l_{1}$')
	plt.title('$Phi_{1}$ Efficiency')
	plt.set_cmap('bwr')

	fig_Phi_1_imp_rms      = plt.figure()
	plt.contourf(l_frac_0_arr, l_frac_1_arr, TC_Phi_1_imp_rms, cont_levs)
	plt.colorbar()
	plt.xticks(l_frac_0_arr)
	plt.yticks(l_frac_1_arr)
	plt.xlabel('$l_{0}$')
	plt.ylabel('$l_{1}$')
	plt.title('$Phi_{1}$ Implemented RMS')
	plt.set_cmap('bwr')

	fig_Phi_1_unalt_rms     = plt.figure()
	plt.contourf(l_frac_0_arr, l_frac_1_arr, TC_Phi_1_unalt_rms, cont_levs)
	plt.colorbar()
	plt.xticks(range(len(l_frac_0_arr)), l_frac_0_arr)
	plt.yticks(range(len(l_frac_1_arr)), l_frac_1_arr)
	plt.xlabel('$l_{0}$')
	plt.ylabel('$l_{1}$')
	plt.title('$Phi_{1}$ Unaltered RMS')
	plt.set_cmap('bwr')

	# ----------------- Plot Phi 5
	fig_Phi_5	           = plt.figure()
	TC_Phi_5_Norm          = np.divide(TC_Phi_5_imp_avg, TC_Phi_5_unalt_avg)
	plt.contourf(l_frac_0_arr, l_frac_1_arr, TC_Phi_5_Norm, cont_levs)
	cbar 			       = plt.colorbar()
	cbar.set_label('${T_{imp}}/{T_{unalt}}$')
	plt.xticks(l_frac_0_arr)
	plt.yticks(l_frac_1_arr)
	plt.xlabel('$l_{0}$')
	plt.ylabel('$l_{1}$')
	plt.title('$Phi_{5}$ Efficiency')
	plt.set_cmap('bwr')

	fig_Phi_5_imp_rms      = plt.figure()
	plt.contourf(l_frac_0_arr, l_frac_1_arr, TC_Phi_5_imp_rms, cont_levs)
	plt.colorbar()
	plt.xticks(l_frac_0_arr)
	plt.yticks(l_frac_1_arr)
	plt.xlabel('$l_{0}$')
	plt.ylabel('$l_{1}$')
	plt.title('$Phi_{5}$ Implemented RMS')
	plt.set_cmap('bwr')

	fig_Phi_5_unalt_rms     = plt.figure()
	plt.contourf(l_frac_0_arr, l_frac_1_arr, TC_Phi_5_unalt_rms, cont_levs)
	plt.colorbar()
	plt.xticks(l_frac_0_arr)
	plt.yticks(l_frac_1_arr)
	plt.xlabel('$l_{0}$')
	plt.ylabel('$l_{1}$')
	plt.title('$Phi_{1}$ Unaltered RMS')
	plt.set_cmap('bwr')

	# ----------------- Plot A
	fig_A	           = plt.figure()
	TC_A_Norm          = np.divide(TC_A_imp_avg, TC_A_unalt_avg)
	plt.contourf(l_frac_0_arr, l_frac_1_arr, TC_A_Norm, cont_levs)
	cbar 			   = plt.colorbar()
	cbar.set_label('${T_{imp}}/{T_{unalt}}$')
	plt.xticks(l_frac_0_arr)
	plt.yticks(l_frac_1_arr)
	plt.xlabel('$l_{0}$')
	plt.ylabel('$l_{1}$')
	plt.title('A Efficiency')
	plt.set_cmap('bwr')

	fig_A_imp_rms      = plt.figure()
	plt.contourf(l_frac_0_arr, l_frac_1_arr, TC_A_imp_rms, cont_levs)
	plt.colorbar()
	plt.xticks(l_frac_0_arr)
	plt.yticks(l_frac_1_arr)
	plt.xlabel('$l_{0}$')
	plt.ylabel('$l_{1}$')
	plt.title('A Implemented RMS')
	plt.set_cmap('bwr')

	fig_A_unalt_rms     = plt.figure()
	plt.contourf(l_frac_0_arr, l_frac_1_arr, TC_A_unalt_rms, cont_levs)
	plt.colorbar()
	plt.xticks(l_frac_0_arr)
	plt.yticks(l_frac_1_arr)
	plt.xlabel('$l_{0}$')
	plt.ylabel('$l_{0}$')
	plt.title('A Unaltered RMS')
	plt.set_cmap('bwr')

	plt.close('all')

	return fig_R, fig_R_imp_rms, fig_R_unalt_rms, fig_Phi_1, fig_Phi_1_imp_rms, fig_Phi_1_unalt_rms, fig_Phi_5, fig_Phi_5_imp_rms, fig_Phi_5_unalt_rms, fig_A, fig_A_imp_rms, fig_A_unalt_rms
